org: vladkvlchk
app: shortlinker
service: shortlinker
frameworkVersion: "3"

custom:
  tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [LinksTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  sign-up:
    handler: build/functions/sign-up.handler
    events:
      - http:
          path: serverlessSetup/auth/sign-up
          method: post
  sign-in:
    handler: build/functions/sign-in.handler
    events:
      - http:
          path: serverlessSetup/auth/sign-in
          method: post
  create-link:
    handler: build/functions/create-link.handler
    events:
      - http:
          path: link/create
          method: post
  deleting-expired-links:
    handler: build/functions/deleting-expired-links.handler
    events:
      - schedule: rate(1 day)

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    LinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Links
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dotenv-plugin
